### ISSUE TITLE
Distribute via update site

### ISSUE THREAD

**Issue by imagejan** [Llamero/Quiver_Plot#1]
Congratulations, this seems to be a nice tool!

I suggest setting up an [update site](http://imagej.net/How_to_set_up_and_populate_an_update_site) for easy installation, so that users don't have to manually copy files into their `./plugins` directory, and they'll automatically receive updates when you release new versions.

**Comment by Llamero** [comment]
Resolved, an update site title, "UCB Vision Sciences" has been setup.
