### ISSUE TITLE
Make the source code available

### ISSUE THREAD

**Issue by imagejan** [Llamero/Quiver_Plot#2]
Your project description says this plugin is published under GPL. Would you mind sharing the source code instead of the jar file only?
I think this plugin might integrate well with the other Flow Analysis tools in Fiji: [FlowJ](https://github.com/fiji/FlowJ), [PIV analysis](https://github.com/fiji/PIV_analyser), and the [mpicbg optic flow analysis tools](https://github.com/axtimwalde/mpicbg/tree/master/mpicbg_/src/main/java/mpicbg/ij/plugin).

**Comment by Llamero** [comment]
Fixed.  I didn't realize until later that JARs cannot be decompiled back to the source code.

Thanks for the heads-up,
   Ben Smith

**Comment by Llamero** [comment]
This repository has now been Mavenized.
